class vec3:
    x: float
    y: float
    z: float

    def __new__(vec: vec3) -> vec3: ...
    def __new__(vec: tuple[float, float, float]) -> vec3: ...
    def __new__(x: float=0, y: float=0, z: float=0) -> vec3: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
